from setuptools import setup, find_packages

setup(
    name="ganabosques_risk_package",
    version="0.1.0",
    description="Package to estimate alert related to deforestation and protected areas using MRV protocol from Colombia",
    author="Steven Sotelo",
    author_email="h.sotelo@cgiar.org",
    packages=find_packages(),
    install_requires=[
        "affine==2.4.0",
        "attrs==25.3.0",
        "certifi==2025.4.26",
        "click==8.2.1",
        "click-plugins==1.1.1",
        "cligj==0.7.2",
        "colorama==0.4.6",
        "fiona==1.10.1",
        "geopandas==1.0.1",
        "mongomock==4.3.0",
        "numpy==2.2.6",
        "packaging==25.0",
        "pandas==2.2.3",
        "pyogrio==0.11.0",
        "pyparsing==3.2.3",
        "pyproj==3.7.1",
        "python-dateutil==2.9.0.post0",
        "pytz==2025.2",
        "rasterio==1.4.3",
        "sentinels==1.0.0",
        "shapely==2.1.1",
        "six==1.17.0",
        "tqdm==4.67.1",
        "tzdata==2025.2"
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
)
