name: Ganabosques Risk Package CI/CD

on:
  push:
    branches: [ "main", "stage" ]
    tags:
      - 'v*'

permissions:
  contents: read

jobs:

  TestGanabosquesRisk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas geopandas shapely rasterio numpy mongomock

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p 'test_*.py'

  MergeToMain:
    needs: [TestGanabosquesRisk]
    name: Merge Stage with Main
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge stage -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: main
          github_token: ${{ github.token }}

  ReleaseGanabosquesRisk:
    needs: MergeToMain
    name: Create and Upload Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Zip Risk Package
        run: zip -r releaseGanabosquesRisk.zip ganabosques_risk_package/ setup.py README.md tests/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GanabosquesRisk
          path: releaseGanabosquesRisk.zip

      - name: Generate Tagname
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES : stage,main
          BRANCH_HISTORY: last

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          release_name: Release ${{ steps.taggerDryRun.outputs.new_tag }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releaseGanabosquesRisk.zip
          asset_name: releaseGanabosquesRisk.zip
          asset_content_type: application/zip

      - name: Update version in setup.py
        run: |
          sed -i "s/version='.*'/version='${{ steps.taggerDryRun.outputs.new_tag }}'/" setup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update version to ${{ steps.taggerDryRun.outputs.new_tag }}"